name: Hourly Vercel Trigger

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          curl -X GET "https://www.mawtinalriyf.com/api/admin/cron/analytics"
